modbus:
  - name: "VSR300"
    type: tcp
    host: 192.168.10.101    #USER SPECIFIC
    port: 8432              #USER SPECIFIC
#Add one tiny sensor here just to keep the hub alive
    sensors:
      - name: "VSR300 Link"
        address: 12101
        slave: 1
